name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache mdBook binaries
        id: cache-binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-mdbook-plugins-v1

      - name: Install Rust Toolchain
        if: steps.cache-binaries.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        if: steps.cache-binaries.outputs.cache-hit != 'true'
        uses: cargo-bins/cargo-binstall@main

      - name: Install mdBook and plugins
        if: steps.cache-binaries.outputs.cache-hit != 'true'
        run: |
          cargo binstall -y mdbook
          cargo binstall -y mdbook-sitemap
          cargo binstall -y mdbook-linkcheck
          cargo binstall -y mdbook-mermaid
          
      - name: Build mdBook
        run: mdbook build

      - name: Copy file from ./public
        run: mv ./public/* ./book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
