name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook and plugins
        uses: taiki-e/install-action@v2
        with:
          tool: >
            mdbook,
            mdbook-sitemap-generator,
            mdbook-linkcheck,
            mdbook-mermaid,
            mdbook-admonish,
            mdbook-external-links

      - name: Build mdBook
        run: mdbook build

      - name: Copy file from ./public
        run: mv ./public/* ./book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
